[versions]
junit = "5.9.2"
alchemist = "25.14.6"
scalapy = "0.5.3"
scala2 = "2.13.10"
junitCore = "4.13.2"
slf4j = "2.0.6"
logback = "1.4.5"

[libraries]
junit-api = {module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit"}
junit-engine = {module = "org.junit.jupiter:junit-jupiter-engine", version.ref="junit"}
junit = {module = "junit:junit", version.ref = "junitCore"}
scala2 = {module = "org.scala-lang:scala-library", version.ref = "scala2"}
scalapy = {module = "dev.scalapy:scalapy-core_2.13", version.ref = "scalapy"}
alchemist = {module = "it.unibo.alchemist:alchemist", version.ref = "alchemist"}
alchemistScafi = {module = "it.unibo.alchemist:alchemist-incarnation-scafi", version.ref = "alchemist"}
slf4j = {module = "org.slf4j:slf4j-api", version.ref = "slf4j"}
logback = {module = "ch.qos.logback:logback-classic", version.ref = "logback"}
alchemistGui = {module = "it.unibo.alchemist:alchemist-swingui", version.ref = "alchemist"}